---
- id: packer_fmt
  name: Packer fmt
  description: Rewrites all Packer configuration files to a canonical format.
  entry: hooks/packer_fmt.sh
  language: script
  files: (packer\.json|\.pkr\.hcl|\.pkrvars\.hcl)$

- id: packer_validate
  name: Packer validate
  description: Validates all Packer configuration files.
  require_serial: true
  entry: hooks/packer_validate.sh
  language: script
  files: (packer\.json|\.pkr\.hcl)$
