---
# Hooks should be listed alphabetically by id.
- description: This hook runs `packer fmt` on appropriate files.
  entry: hooks/packer_fmt.sh
  files: \.pkr(?:vars)?\.hcl$
  id: packer_fmt
  language: script
  name: Packer Format

- description: This hook runs `packer validate` on appropriate files.
  entry: hooks/packer_validate.sh
  files: \.pkr\.hcl$
  id: packer_validate
  language: script
  name: Packer Validate
