---
# Hooks should be listed alphabetically by id.
- description: This hook runs `packer fmt` on appropriate files.
  entry: hooks/packer_fmt.sh
  files: \.pkr(?:vars)?\.hcl$
  id: packer_fmt
  language: script
  name: Packer Format

- description: This hook runs `packer validate` on appropriate files.
  entry: hooks/packer_validate.sh
  files: \.pkr\.hcl$
  id: packer_validate
  language: script
  name: Packer Validate
  # This is necessary because Packer's plugin cache is not safe for concurrent access
  # per https://github.com/hashicorp/terraform/issues/32915#issuecomment-1485061999. If
  # this is not set to true then pre-commit itself will perform some level of
  # parallelization across the files to run this hook against. Since we only care about
  # unique directory paths it should not impact performance and it will help prevent
  # issues arising from concurrent attempts to perform `packer init` on a particular
  # directory path.
  require_serial: true
