---
- id: packer_validate
  name: Packer Validate
  description: This hook runs `packer validate` on appropriate files.
  entry: hooks/packer_validate.sh
  language: script
  files: \.pkr\.hcl$
  pass_filenames: true

- id: packer_fmt
  name: Packer Format
  description: This hook runs `packer fmt` on appropriate files.
  entry: hooks/packer_fmt.sh
  language: script
  files: \.pkr(?:vars)?\.hcl$
  pass_filenames: true
